name: Deploy to EC2

on:
  push:
    branches:
      - main # Change this to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: SSH into EC2 and deploy
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_SERVER_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/miranda_laravel
            git config --global --add safe.directory /var/www/miranda_laravel
            sudo git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            sudo systemctl restart nginx  # Replace with your web service if different (e.g., apache2)
