name: Deploy Miranda Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Install SSH Key
        uses: webfactory/ssh-agent@latest
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Run deployment commands on the server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no mikelmindieta@123.45.67.89 << 'EOF'
          cd /path/to/Miranda

          # Pull the latest code
          git pull origin main

          # Install Python dependencies
          pip install -r requirements.txt

          # Install Laravel dependencies
          composer install

          # Run Django migrations
          python manage.py migrate

          # Run Laravel migrations
          php artisan migrate

          # Restart the server
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx

          # For Apache, use:
          # sudo systemctl restart apache2

          EOF
